export type GalleryCategory = 'All' | 'People' | 'Food' | 'Stalls' | 'Music' | 'Decor';

export type GalleryItem = {
  id: number;
  src: string;
  title: string;
  caption: string;
  category: Exclude<GalleryCategory, 'All'>;
  accent: string;
  size: 'sm' | 'md' | 'lg';
};

export const galleryCategories: GalleryCategory[] = [
  'All',
  'People',
  'Food',
  'Stalls',
  'Music',
  'Decor',
];

export const fleaMarketGallery: GalleryItem[] = [
  {
    id: 1,
    src: '/flea market/Copy of _JEE0475.JPG',
    title: 'Golden Hour Crowd',
    caption: 'A warm rush of visitors moving through the flea market lanes.',
    category: 'People',
    accent: 'from-[#FF8A00]/90 via-[#FF4D6D]/60 to-transparent',
    size: 'lg',
  },
  {
    id: 2,
    src: '/flea market/Copy of _JEE0741.JPG',
    title: 'Main Stage Pulse',
    caption: 'Music, movement, and cheering energy taking over the evening.',
    category: 'Music',
    accent: 'from-[#8B5CF6]/90 via-[#22D3EE]/60 to-transparent',
    size: 'lg',
  },
  {
    id: 3,
    src: '/flea market/Copy of 20250420_140135.jpg',
    title: 'Street Flavours',
    caption: 'Food counters serving quick bites and colorful treats.',
    category: 'Food',
    accent: 'from-[#F97316]/90 via-[#FDBA74]/60 to-transparent',
    size: 'md',
  },
  {
    id: 4,
    src: '/flea market/Copy of Copy of IMG_6074.JPG',
    title: 'Decor Details',
    caption: 'Textures, lights, and handcrafted elements setting the mood.',
    category: 'Decor',
    accent: 'from-[#F43F5E]/90 via-[#FDA4AF]/60 to-transparent',
    size: 'sm',
  },
  {
    id: 5,
    src: '/flea market/Copy of Copy of IMG_9404.JPG',
    title: 'Maker Booth Stories',
    caption: 'Stalls filled with conversation, discovery, and handmade finds.',
    category: 'Stalls',
    accent: 'from-[#F59E0B]/90 via-[#FDE68A]/60 to-transparent',
    size: 'lg',
  },
  {
    id: 6,
    src: '/flea market/Copy of Copy of IMG_9536.JPG',
    title: 'Festival Portraits',
    caption: 'Candid smiles and expressive moments from the crowd.',
    category: 'People',
    accent: 'from-[#3B82F6]/90 via-[#93C5FD]/60 to-transparent',
    size: 'md',
  },
  {
    id: 7,
    src: '/flea market/Copy of IMG_6089.JPG',
    title: 'Color Pop Stall',
    caption: 'A vivid corner of crafts, keepsakes, and local creativity.',
    category: 'Stalls',
    accent: 'from-[#E879F9]/90 via-[#F5D0FE]/60 to-transparent',
    size: 'sm',
  },
  {
    id: 8,
    src: '/flea market/Copy of IMG_6093.JPG',
    title: 'Quick Bite Corner',
    caption: 'Flavor-packed plates and a queue that never stayed still.',
    category: 'Food',
    accent: 'from-[#FB7185]/90 via-[#FECDD3]/60 to-transparent',
    size: 'sm',
  },
  {
    id: 9,
    src: '/flea market/Copy of IMG_7208.JPG',
    title: 'Ambient Installations',
    caption: 'Decor-led storytelling woven into every walkway.',
    category: 'Decor',
    accent: 'from-[#14B8A6]/90 via-[#99F6E4]/60 to-transparent',
    size: 'md',
  },
  {
    id: 10,
    src: '/flea market/Copy of IMG_9234.JPG',
    title: 'Rhythm In Motion',
    caption: 'Live performances pulling the audience closer to the stage.',
    category: 'Music',
    accent: 'from-[#6366F1]/90 via-[#A5B4FC]/60 to-transparent',
    size: 'md',
  },
  {
    id: 11,
    src: '/flea market/Copy of IMG_9508.JPG',
    title: 'Friends At The Fair',
    caption: 'Group moments that made the evening feel personal.',
    category: 'People',
    accent: 'from-[#0EA5E9]/90 via-[#7DD3FC]/60 to-transparent',
    size: 'lg',
  },
  {
    id: 12,
    src: '/flea market/Copy of IMG_9527.JPG',
    title: 'Curated Corners',
    caption: 'Every stall holding a different aesthetic and story.',
    category: 'Stalls',
    accent: 'from-[#84CC16]/90 via-[#D9F99D]/60 to-transparent',
    size: 'md',
  },
  {
    id: 13,
    src: '/flea market/Copy of RY3A9419.JPG',
    title: 'Neon Atmosphere',
    caption: 'Decor lighting shifting the market into an evening dreamscape.',
    category: 'Decor',
    accent: 'from-[#A855F7]/90 via-[#E9D5FF]/60 to-transparent',
    size: 'lg',
  },
  {
    id: 14,
    src: '/flea market/Copy of RY3A9429.JPG',
    title: 'Acoustic Session',
    caption: 'A softer music moment layered into the broader festival energy.',
    category: 'Music',
    accent: 'from-[#06B6D4]/90 via-[#A5F3FC]/60 to-transparent',
    size: 'sm',
  },
  {
    id: 15,
    src: '/flea market/Copy of RY3A9556.JPG',
    title: 'Handmade Finds',
    caption: 'Visitors pausing to explore pieces made with care.',
    category: 'Stalls',
    accent: 'from-[#F97316]/90 via-[#FED7AA]/60 to-transparent',
    size: 'lg',
  },
  {
    id: 16,
    src: '/flea market/Copy of RY3A9638.JPG',
    title: 'Crowd Chemistry',
    caption: 'Shared reactions, spontaneous laughter, and festival warmth.',
    category: 'People',
    accent: 'from-[#EC4899]/90 via-[#FBCFE8]/60 to-transparent',
    size: 'sm',
  },
  {
    id: 17,
    src: '/flea market/Copy of RY3A9665.JPG',
    title: 'Signature Plates',
    caption: 'Food that looked as lively as the market itself.',
    category: 'Food',
    accent: 'from-[#F59E0B]/90 via-[#FDE68A]/60 to-transparent',
    size: 'md',
  },
  {
    id: 18,
    src: '/flea market/Copy of RY3A9681.JPG',
    title: 'Glowing Pathways',
    caption: 'Decor accents guiding people from one discovery to the next.',
    category: 'Decor',
    accent: 'from-[#22C55E]/90 via-[#BBF7D0]/60 to-transparent',
    size: 'md',
  },
  {
    id: 19,
    src: '/flea market/Copy of RY3A9710.JPG',
    title: 'Food Rush',
    caption: 'Busy counters and the constant pull of fresh aromas.',
    category: 'Food',
    accent: 'from-[#EF4444]/90 via-[#FECACA]/60 to-transparent',
    size: 'lg',
  },
  {
    id: 20,
    src: '/flea market/Copy of RY3A9727.JPG',
    title: 'Closing Crescendo',
    caption: 'A high-energy final stretch that held the whole vibe together.',
    category: 'Music',
    accent: 'from-[#8B5CF6]/90 via-[#C4B5FD]/60 to-transparent',
    size: 'lg',
  },
];
